---
title: Iterative Release Blueprint
---

flowchart TD

id1((start))-->A(Backlog Refinement)
A-->B(Sprint Planning)

id2>Wednesday]
B

B-->id3{break}

id3{break}-->C(Mob Programming - development)
id3{break}-->D(Mob Programming - unit)-->F(Mob Programming - integration)
id3{break}-->E(Mob Programming - automation)

D(Mob Programming - unit)-->id4{break}
E(Mob Programming - automation)-->|automation is run to identify flow blockers|id4{break}
F(Mob Programming - integration)-->id4{break}

id4{break}-->G(QA - flow blockers)

E(Mob Programming - automation)-->id5{break}-->H(QA - automation testing)

H(QA-automation testing)-->X(SERVICE BASED RELEASE)
G(QA - flow blockers)-->X(SERVICE BASED RELEASE)

H(QA - automation testing)-->|passed qa|Y(SERVICE BASED RELEASE)

X(SERVICE BASED RELEASE)-->|story complete|K(Pilot Testing - black box)
K-->L(Flag on for Client)

Y(SERVICE BASED RELEASE)