---
title: PagerDuty Flowchart
---
flowchart LR

subgraph Observability
    A(terraform)
end

subgraph All Incident Types
    subgraph Datadog Monitoring
        B(sythentic tests)
        A(terraform)-.->C(monitors)
    end
    D(andon)
    A(terraform)-.->D(andon)
    E(custom incident)
    F(looker)
end

E(custom incident)-->G(Events API 2)
F(looker)-->G(Events API 2)

G(Events API 2)-->H(PagerDuty New Incident)

%% style A fill:#f9f,stroke:#333,stroke-width:4px
%% style Observability font-weight:bold