---
title: Feature Flags vs. Regression Tests
---
flowchart LR

    flowchart LR

    A[/master branch\] --regression tests -->B[/master branch\]-->E[/new branch\]
    C[/feature branch\] -.regression tests .->D[/feature branch\]
    D[/feature branch\] -.combine tests .-> E[/new master branch\]