---
title: Feature Flags vs. Regression Tests
---
flowchart LR

    Z[Start]-->A[/master branch\]--regression tests-->B[/master branch\]--regression tests-->E[/new master branch\]
    A[/master branch\]-.->C[/feature branch\]
    subgraph feature-flag
    C[/feature branch\]-.write regression tests .->D[/feature branch\]
    D[/feature branch\]
    end feature-flag
    D[/feature branch\]-.combine tests .->E[/new master branch\]