---
title: Iterative Release Blueprint
---

flowchart TD

id1((start))-->A(Backlog Refinement)
A(Backlog Refinement)-->B(Sprint Planning)

B(Sprint Planning)-->id2>Wednesday]

B(Sprint Planning)-->id3{break}